### ISSUE TITLE
Dependencies configuration does not specify required Node.js version

### ISSUE THREAD

**Issue by ltfschoen** [AcalaNetwork/acala-dapp#165]
**My Acala Mandala Address: 5F2QSwPHobet1pLFTEw6mkcT8bwZdEMmHfBGYPkiK7Pgxdex**

If I used the latest Node.js version v14.7, it generates the following error, and it doesn't specify what version is compatible.

```
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@polkadot/dev > @typescript-eslint/eslint-plugin@2.31.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "@polkadot/dev > @typescript-eslint/parser@2.31.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "@polkadot/dev > babel-plugin-styled-components@1.10.7" has unmet peer dependency "styled-components@>= 2".
warning " > eslint-plugin-header@3.0.0" has unmet peer dependency "eslint@>=0.18.0".
warning " > eslint-plugin-node@11.1.0" has unmet peer dependency "eslint@>=5.16.0".
warning " > eslint-plugin-sort-destructure-keys@1.3.5" has unmet peer dependency "eslint@3 - 7".
warning " > eslint-plugin-standard@4.0.1" has unmet peer dependency "eslint@>=5.0.0".
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning " > @typescript-eslint/eslint-plugin@2.34.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@2.34.0" has unmet peer dependency "eslint@*".
warning " > @typescript-eslint/parser@2.34.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/apps > @apollo/react-hooks@3.1.5" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/apps > @apollo/react-hooks@3.1.5" has incorrect peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/page-governance > @polkadot/react-identicon@0.52.1" has unmet peer dependency "@polkadot/keyring@*".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/page-governance > @polkadot/react-identicon@0.52.1" has unmet peer dependency "@polkadot/util@*".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/page-governance > @polkadot/react-identicon@0.52.1" has unmet peer dependency "@polkadot/util-crypto@*".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/page-governance > @polkadot/react-identicon@0.52.1" has unmet peer dependency "react-is@*".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/react-components > @polkadot/ui-keyring@0.53.1" has unmet peer dependency "@polkadot/keyring@*".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/react-components > @polkadot/ui-keyring@0.53.1" has unmet peer dependency "@polkadot/ui-settings@*".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/react-components > @polkadot/ui-keyring@0.53.1" has unmet peer dependency "@polkadot/util@*".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/apps > @apollo/react-hooks > @apollo/react-common@3.1.4" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/apps > @apollo/react-hooks > @apollo/react-common@3.1.4" has unmet peer dependency "apollo-utilities@^1.3.2".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/apps > @apollo/react-hooks > @apollo/react-common@3.1.4" has incorrect peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/page-governance > @polkadot/react-identicon > @polkadot/ui-settings@0.52.1" has unmet peer dependency "@polkadot/util@*".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/page-governance > @polkadot/react-identicon > @polkadot/ui-shared@0.52.1" has unmet peer dependency "@polkadot/util@*".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/page-governance > @polkadot/react-identicon > @polkadot/ui-shared@0.52.1" has unmet peer dependency "@polkadot/util-crypto@*".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/page-governance > @polkadot/react-identicon > styled-components@5.1.1" has unmet peer dependency "react-is@>= 16.8.0".
warning "workspace-aggregator-8786ab7a-82f5-46b7-a3ee-a8c2fc1468e3 > @acala-dapp/ui-components > antd > rc-picker@1.10.7" has unmet peer dependency "dayjs@^1.8.18".
[4/4] 🔨  Building fresh packages...
[-/10] ⠠ waiting...
[9/10] ⠐ usb
[-/10] ⠐ waiting...
[8/10] ⠐ node-hid
warning Error running install script for optional dependency: "/Users/ls/code/src/ltfschoen/acala-dapp/node_modules/usb: Command failed.
Exit code: 1
Command: prebuild-install --verbose || node-gyp rebuild
Arguments: 
Directory: /Users/ls/code/src/ltfschoen/acala-dapp/node_modules/usb
Output:
prebuild-install info begin Prebuild-install version 5.3.5
prebuild-install info looking for cached prebuild @ /Users/ls/.npm/_prebuilds/b3cd0a-usb-v1.6.3-node-v83-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v83-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v83-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.7.0 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.7.0 | darwin | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/ls/code/src/ltfschoen/acala-dapp/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ls/code/src/ltfschoen/acala-dapp/node_modules/usb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ls/code/src/ltfschoen/acala-dapp/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ls/.node-gyp/14.7.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ls/.node-gyp/14.7.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ls/code/src/ltfschoen/acala-dapp/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ls/.node-gyp/14.7.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ls/code/src/ltfschoen/acala-dapp/node_modules/usb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ls/code/src/ltfschoen/acala-dapp/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command \"/Users/ls/.nvm/versions/node/v14.7.0/bin/node\" \"/Users/ls/code/src/ltfschoen/acala-dapp/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/ls/code/src/ltfschoen/acala-dapp/node_modules/usb
✨  Done in 184.68s.
```

If I switch to the latest stable LTS version v12.18.3 it works

**Comment by qwer951123** [comment]
I had checked my local work environment and my node version is 14.4, maybe some other problem occurs this error.

**Comment by ltfschoen** [comment]
@qwer951123 See this PR https://github.com/AcalaNetwork/acala-dapp/pull/166. It works with Node.js v12.18.3 LTS

**Comment by xlc** [comment]
> gyp: No Xcode or CLT version detected!

does not look like nodejs issue

**Comment by qwer951123** [comment]
> @qwer951123 See this PR #166. It works with Node.js v12.18.3 LTS
<img width="445" alt="Screen Shot 2020-07-30 at 7 09 11 PM" src="https://user-images.githubusercontent.com/4833280/88916159-283a6900-d298-11ea-9f05-e98937ad65e1.png">
I tried on a ubuntu VPS and succeeded with node v14.0.0. Maybe you can delete yarn.lock file and retry with node >=14.0.0 again?
