### ISSUE TITLE
TypeError: api.query.stakingPool.stakingPoolParams is not a function

### ISSUE THREAD

**Issue by imstar15** [AcalaNetwork/acala-dapp#328]
1. I am using acala-dapp to connect to the acala private network and encounter this error. How can I solve it?

- Use https://apps.acala.network/ to connect to the acala private network, no error is reported.
- Use the acala-dapp I built to connect to acala mandala, there is no error.
- my code is pulled from master, commit b6599878ca42b46ee28ce73ae98649b3257cba1b

```
node_modules/@acala-network/api-derive/homa/staking-pool.js:40
  37 | function stakingPool(instanceId, api) {
  38 |   return (0, _util.memo)(instanceId, () => {
  39 |     const constants = getConstants(api);
> 40 |     return (0, _rxjs.combineLatest)([api.query.stakingPool.currentEra(), api.query.stakingPool.nextEraUnbond(), api.query.stakingPool.totalClaimedUnbonded(), api.query.stakingPool.totalBonded(), api.query.stakingPool.unbondingToFree(), api.query.stakingPool.freeUnbonded(), api.query.stakingPool.stakingPoolParams(), api.query.tokens.totalIssuance(constants.liquidCurrency)]).pipe((0, _operators.map)(result => {
  41 |       const [currentEra, nextEraUnbond, totalClaimedUnbonded, totalBonded, unbondingToFree, freeUnbonded, stakingPoolParams, liquidTokenIssuance] = result;
  42 |       return _objectSpread({
  43 |         currentEra: currentEra,
View compiled
Observable._subscribe
node_modules/@polkadot/api-derive/util/memo.js:27
  24 | /** @internal */
  25 | function memo(instanceId, inner) {
  26 |   const cached = (0, _memoizee.default)((...params) => new _rxjs.Observable(observer => {
> 27 |     const subscription = inner(...params).subscribe(observer);
  28 |     return () => {
  29 |       cached.delete(...params);
  30 |       subscription.unsubscribe();
```
![image](https://user-images.githubusercontent.com/16951509/101769939-b2d28500-3b22-11eb-8f4d-a986e107c049.png)

2. I encountered the following error when configuring the faucet project. How can I solve it?

```
0|pm2-inte | [pm2-intercom:1.0.0] ready

1|faucet  | 2020-12-10 21:59:55        API/INIT: RPC methods not decorated: grandpa_proveFinality
1|faucet  | Unable to resolve type BountyIndex, it will fail on construction
1|faucet  | Unable to resolve type PalletsOrigin, it will fail on construction
1|faucet  | Unable to resolve type ScheduleTaskIndex, it will fail on construction
1|faucet  | Unable to resolve type ClassId, it will fail on construction
1|faucet  | Unable to resolve type TokenId, it will fail on construction
1|faucet  | Unable to resolve type DestAddress, it will fail on construction
1|faucet  | Unknown types found, no types for AsOriginId, Bounty, BountyIndex, CID, ClassId, ClassInfoOf, DestAddress, DispatchTime, PalletsOrigin, PoolId, PoolInfo, Position, Properties, ScheduleTaskIndex, TokenId, TokenInfoOf, TradingPair
1|faucet  | 2020-12-10 21:59:58        API/INIT: Error: FATAL: Unable to initialize the API: createType(BountyIndex):: Cannot construct unknown type BountyIndex
1|faucet  |     at EventEmitter.value (/Users/star/devlab/faucet-bot/node_modules/@polkadot/api/base/Init.js:85:25)
1|faucet  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
1|faucet  |     at runNextTicks (internal/process/task_queues.js:62:3)
1|faucet  |     at processImmediate (internal/timers.js:434:9)
1|faucet  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|faucet  | Error: FATAL: Unable to initialize the API: createType(BountyIndex):: Cannot construct unknown type BountyIndex
1|faucet  |     at EventEmitter.value (/Users/star/devlab/faucet-bot/node_modules/@polkadot/api/base/Init.js:85:25)
1|faucet  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
1|faucet  |     at runNextTicks (internal/process/task_queues.js:62:3)
1|faucet  |     at processImmediate (internal/timers.js:434:9)

```

**Comment by qwer951123** [comment]
the app only supports tc5 now, we will support the latest mandala dev chain soon or later.

**Comment by imstar15** [comment]
My private network is tc5, but this error still occurs.

Acala private network: tc5, https://github.com/AcalaNetwork/Acala/releases/tag/0.6.2
system: macOS 11.0.1 

@qwer951123

**Comment by qwer951123** [comment]
<img width="999" alt="截屏2020-12-15 下午1 47 27" src="https://user-images.githubusercontent.com/4833280/102176297-191d2600-3edc-11eb-93cb-795e12191380.png">
1. It makes me confused, you can use the console and check if your private network has this storage.
2. faucet should update the @acala-network/api package's version to 0.4.0-beta.34

**Comment by imstar15** [comment]
![image](https://user-images.githubusercontent.com/16951509/103171466-71163e00-4887-11eb-886b-65eb3f87bca0.png)

It does not have this storage.
@qwer951123

**Comment by imstar15** [comment]
You version is 606
My version is 602

Why is there this difference?

My environment:
OS: macOS 11
network: Acala private network, 0.6.2 (https://github.com/AcalaNetwork/Acala/releases/tag/0.6.2)

**Comment by imstar15** [comment]
I checkout another Acala version, And Delete db, relaunch private network. It works!
```
git checkout -b staking f168ce6b
make init
rm -rf /tmp/alice 
rm -rf /tmp/bob
./acala --base-path /tmp/alice --chain local --alice --port 30333 --ws-port 9944 --rpc-port 9933  --validator --rpc-methods=Unsafe --ws-external --rpc-external --ws-max-connections 1000 --rpc-cors=all --unsafe-ws-external --unsafe-rpc-external
./acala --base-path /tmp/bob --chain local --bob --port 30334 --ws-port 9945 --rpc-port 9934  --validator --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWNHQzppSeTxsjNjiX6NFW1VCXSJyMBHS48QBmmGs4B3B9
```
